FROM node:hydrogen-alpine3.21

#WORKDIR /myapp/


#RUN npm init -y && npm install express

#COPY ./nodejs-app.js .


EXPOSE 3000
EXPOSE 22
#ENTRYPOINT ["node" , "nodejs-app.js"]

ENTRYPOINT ["/bin/sh"]

