apiVersion: v1
kind: Service
metadata: 
  name: node-app-loadbalancer
spec:
  
  type: NodePort 
  selector:
    app: node
  ports:
    - nodePort: 30001
      port: 3000
      targetPort: 3000
      protocol: TCP

